[package]
name = "fprintjs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.30", features = ["derive"] }
log = "0.4.25"
simple_logger = "5.0.0"
tar = "0.4.43"
yara = { version = "0.29.0", features = [] }
zstd = "0.13.2"
